"use client";
// src/app/page.tsx — Drona Landing Page
import { signIn, useSession } from "next-auth/react";
import { useRouter } from "next/navigation";
import React, { useEffect, useRef, useState } from "react";
import { motion, useScroll, useTransform } from "framer-motion";
import Image from "next/image";


/* ---- Subject chips with icons ---- */
const subjects = [
  { name: "DSA", icon: "🌲", desc: "Data Structures & Algorithms" },
  { name: "DBMS", icon: "🗄️", desc: "Database Management Systems" },
  { name: "OS", icon: "💻", desc: "Operating Systems" },
  { name: "CNS", icon: "🔐", desc: "Cryptography & Network Security" },
  { name: "Python", icon: "🐍", desc: "Python Programming" },
  { name: "Java", icon: "☕", desc: "Java Programming" },
  { name: "Physics", icon: "⚛️", desc: "Physics" },
  { name: "Calculus", icon: "∫", desc: "Calculus" },
  { name: "Biology", icon: "🧬", desc: "Biology" },
  { name: "Web Dev", icon: "🌐", desc: "Web Programming" },
  { name: "DAA", icon: "📊", desc: "Design & Analysis of Algorithms" },
  { name: "Probability", icon: "📈", desc: "Probability & Statistics" },
  { name: "Networks", icon: "📡", desc: "Computer Networks" },
  { name: "Diff. Calc", icon: "Δ", desc: "Differential Calculus" },
];

const features = [
  { id: "planner",   icon: "📜", title: "AI Study Planner",     desc: "A personalised 4-week study plan generated from first principles to mastery — tailored to your subject and goals." },
  { id: "resources", icon: "🎬", title: "Free Resources",       desc: "Curated YouTube lectures appear for every topic, so you never have to search for learning material." },
  { id: "tests",     icon: "✍️", title: "Mock Tests",           desc: "10 MCQs + 6 short-answers generated by Drona AI — available any time, right from your study plan." },
  { id: "grading",   icon: "📷", title: "Handwritten Grading",  desc: "Photograph your answer sheet — AI reads your handwriting and grades it instantly with detailed evaluation." },
  { id: "feedback",  icon: "📊", title: "Deep Feedback",        desc: "Radar charts and topic-wise analysis reveal exactly where you excel and where to focus next." },
  { id: "paper",     icon: "📋", title: "Paper Analyser",       desc: "Upload a past university paper — Drona generates a matching mock paper in seconds." },
];

/* ---- Vortex Spiral — elongated shards arranged along Archimedean arms ---- */
function VortexSpiral({
  size = 800,
  opacity = 0.28,
  speed = 90,
  reverse = false,
}: {
  size?: number;
  opacity?: number;
  speed?: number;
  reverse?: boolean;
}) {
  const cx = size / 2;
  const cy = size / 2;
  const arms = 3;          // number of spiral arms
  const shardsPerArm = 14; // shards along each arm
  const maxR = size * 0.44;
  const turns = 2.2;

  // Gold palette
  const colors = ["#B8860B", "#DAA520", "#C9A84C", "#8B6914", "#FFD700"];

  const shards: React.ReactNode[] = [];

  for (let arm = 0; arm < arms; arm++) {
    const armOffset = (arm / arms) * 2 * Math.PI;
    for (let s = 1; s <= shardsPerArm; s++) {
      const t = s / shardsPerArm;                      // 0→1 along the arm
      const angle = armOffset + t * turns * 2 * Math.PI;
      const r = t * maxR;
      const x = cx + r * Math.cos(angle);
      const y = cy + r * Math.sin(angle);

      // Shard grows as it moves outward
      const shardLen = 8 + t * 52;   // 8px inner → 60px outer
      const shardW   = 2 + t * 9;

      // Angle pointing radially outward + tangential tilt
      const radialAngle = (angle * 180) / Math.PI + 85;

      const colorIdx = (arm * shardsPerArm + s) % colors.length;
      const col = colors[colorIdx];
      const alpha = 0.35 + t * 0.55; // more opaque outward

      shards.push(
        <ellipse
          key={`${arm}-${s}`}
          cx={x}
          cy={y}
          rx={shardW / 2}
          ry={shardLen / 2}
          fill={col}
          fillOpacity={alpha}
          stroke={col}
          strokeWidth="0.6"
          strokeOpacity={alpha * 0.8}
          transform={`rotate(${radialAngle}, ${x}, ${y})`}
        />
      );
    }
  }

  // Subtle spiral guide path for each arm
  const guidePaths: React.ReactNode[] = Array.from({ length: arms }, (_, arm) => {
    const armOffset = (arm / arms) * 2 * Math.PI;
    const steps = shardsPerArm * 8;
    const pts = Array.from({ length: steps + 1 }, (_, i) => {
      const t = i / steps;
      const angle = armOffset + t * turns * 2 * Math.PI;
      const r = t * maxR;
      const px = cx + r * Math.cos(angle);
      const py = cy + r * Math.sin(angle);
      return `${i === 0 ? "M" : "L"}${px.toFixed(1)},${py.toFixed(1)}`;
    }).join(" ");
    return (
      <path
        key={arm}
        d={pts}
        stroke="#B8860B"
        strokeWidth="0.5"
        strokeOpacity="0.18"
        fill="none"
        strokeLinecap="round"
      />
    );
  });

  return (
    <motion.svg
      width={size}
      height={size}
      viewBox={`0 0 ${size} ${size}`}
      fill="none"
      xmlns="http://www.w3.org/2000/svg"
      style={{ opacity }}
      animate={{ rotate: reverse ? -360 : 360 }}
      transition={{ duration: speed, repeat: Infinity, ease: "linear" }}
    >
      {/* Glow rings at centre */}
      <circle cx={cx} cy={cy} r="18" fill="#DAA520" fillOpacity="0.12" />
      <circle cx={cx} cy={cy} r="8"  fill="#FFD700" fillOpacity="0.22" />
      {guidePaths}
      {shards}
    </motion.svg>
  );
}

/* ---- Mandala (kept as subtle background layer) ---- */
function Mandala({ size = 800, opacity = 0.18, speed = 120 }: { size?: number; opacity?: number; speed?: number }) {
  return (
    <motion.svg
      width={size} height={size} viewBox="0 0 800 800" fill="none"
      xmlns="http://www.w3.org/2000/svg"
      style={{ opacity }}
      animate={{ rotate: 360 }}
      transition={{ duration: speed, repeat: Infinity, ease: "linear" }}
    >
      <circle cx="400" cy="400" r="380" stroke="#B8860B" strokeWidth="1.5" strokeDasharray="8 6"/>
      <circle cx="400" cy="400" r="340" stroke="#C9A84C" strokeWidth="0.8"/>
      {Array.from({length:24}).map((_,i)=>{const a=(i*360/24)*Math.PI/180;return <circle key={i} cx={400+320*Math.cos(a)} cy={400+320*Math.sin(a)} r="14" stroke="#DAA520" strokeWidth="1" fill="none"/>;  })}
      {Array.from({length:16}).map((_,i)=>{const a=(i*360/16)*Math.PI/180,x=400+240*Math.cos(a),y=400+240*Math.sin(a);return <ellipse key={i} cx={x} cy={y} rx="16" ry="30" stroke="#B8860B" strokeWidth="1" fill="none" transform={`rotate(${i*360/16+90},${x},${y})`}/>;  })}
      {Array.from({length:8}).map((_,i)=>{const a=(i*45)*Math.PI/180,x=400+120*Math.cos(a),y=400+120*Math.sin(a);return <ellipse key={i} cx={x} cy={y} rx="22" ry="52" stroke="#DAA520" strokeWidth="1.2" fill="rgba(184,134,11,0.05)" transform={`rotate(${i*45+90},${x},${y})`}/>;  })}
      {Array.from({length:48}).map((_,i)=>{const a=(i*360/48)*Math.PI/180;return <circle key={i} cx={400+365*Math.cos(a)} cy={400+365*Math.sin(a)} r="2.5" fill="#B8860B"/>;  })}
      <circle cx="400" cy="400" r="60" stroke="#DAA520" strokeWidth="1.5"/>
      <circle cx="400" cy="400" r="38" stroke="#C9A84C" strokeWidth="1"/>
      <circle cx="400" cy="400" r="18" fill="rgba(218,165,32,0.12)" stroke="#B8860B" strokeWidth="1.5"/>
      {Array.from({length:6}).map((_,i)=>{const a=(i*60)*Math.PI/180;return <line key={i} x1="400" y1="400" x2={400+58*Math.cos(a)} y2={400+58*Math.sin(a)} stroke="#DAA520" strokeWidth="0.8"/>;  })}
    </motion.svg>
  );
}

/* ---- Corner ornament ---- */
function Corner({ flip = false }: { flip?: boolean }) {
  return (
    <motion.svg width="180" height="180" viewBox="0 0 180 180" fill="none"
      animate={{ rotate: [0, flip ? -4 : 4, 0] }} transition={{ duration: 8, repeat: Infinity, ease: "easeInOut" }}
      style={{ transform: flip ? "scaleX(-1)" : undefined }}>
      {[0,1,2,3,4].map(i => <circle key={i} cx="20" cy="20" r={15+i*16} stroke="#B8860B" strokeWidth="0.7" strokeDasharray={`${3+i} ${3+i}`} opacity={0.5-i*0.08}/>)}
      {Array.from({length:8}).map((_,i)=>{const a=(i*45)*Math.PI/180;return <circle key={i} cx={20+75*Math.cos(a)} cy={20+75*Math.sin(a)} r="3" fill="#DAA520" opacity="0.4"/>;  })}
    </motion.svg>
  );
}

/* ========== MAIN COMPONENT ========== */
export default function LandingPage() {
  const { data: session, status } = useSession();
  const router = useRouter();
  const heroRef = useRef<HTMLDivElement>(null);
  const [activeSection, setActiveSection] = useState("home");
  const [mobileMenuOpen, setMobileMenuOpen] = useState(false);

  // Parallax for hero text
  const { scrollY } = useScroll();
  const heroY = useTransform(scrollY, [0, 400], [0, -60]);
  const heroOpacity = useTransform(scrollY, [0, 300], [1, 0.6]);

  // AOS-like scroll reveal using Intersection Observer
  useEffect(() => {
    if (status === "authenticated") { router.push("/dashboard"); return; }

    const observer = new IntersectionObserver(
      (entries) => entries.forEach((e) => {
        if (e.isIntersecting) {
          e.target.classList.add("aos-animate");
          const sec = e.target.closest("section")?.id;
          if (sec) setActiveSection(sec);
        }
      }),
      { threshold: 0.15 }
    );
    document.querySelectorAll("[data-aos]").forEach((el) => observer.observe(el));
    return () => observer.disconnect();
  }, [status, router]);

  const navLinks = [
    { href: "#home",      label: "Home" },
    { href: "#features",  label: "Features" },
    { href: "#subjects",  label: "Subjects" },
    { href: "#resources", label: "Resources" },
    { href: "#about",     label: "About" },
  ];

  function scrollTo(id: string) {
    document.getElementById(id.replace("#", ""))?.scrollIntoView({ behavior: "smooth" });
    setMobileMenuOpen(false);
  }

  if (status === "loading") return (
    <div className="min-h-screen flex items-center justify-center" style={{ background: "#F5E6C0" }}>
      <div className="flex flex-col items-center gap-3">
        <motion.div className="w-12 h-12 rounded-full border-2"
          style={{ borderColor: "#B8860B", borderTopColor: "transparent" }}
          animate={{ rotate: 360 }} transition={{ duration: 0.8, repeat: Infinity, ease: "linear" }}/>
        <p style={{ fontFamily: "'Cinzel',serif", color: "#8B6914", letterSpacing: "0.2em", fontSize: "0.8rem" }}>PREPARING YOUR PATH…</p>
      </div>
    </div>
  );

  return (
    <main style={{ background: "linear-gradient(160deg,#FDF3DC 0%,#F5E6C0 35%,#EDD890 65%,#F7E8C4 100%)", overflowX: "hidden" }}>

      {/* ===== AOS styles injected ===== */}
      <style>{`
        [data-aos]{opacity:0;transform:translateY(32px);transition:opacity 0.7s ease,transform 0.7s ease;}
        [data-aos].aos-animate{opacity:1;transform:translateY(0);}
        [data-aos-delay="100"]{transition-delay:0.1s;}[data-aos-delay="200"]{transition-delay:0.2s;}
        [data-aos-delay="300"]{transition-delay:0.3s;}[data-aos-delay="400"]{transition-delay:0.4s;}
        [data-aos-delay="500"]{transition-delay:0.5s;}[data-aos-delay="600"]{transition-delay:0.6s;}
        @keyframes goldShimmer{0%{background-position:0% center;}50%{background-position:200% center;}100%{background-position:0% center;}}
        .subject-chip:hover .chip-tooltip{opacity:1;transform:translateY(0);}
        .gold-btn{transition:all 0.3s ease;}
        .gold-btn:hover{transform:translateY(-3px);box-shadow:0 10px 36px rgba(184,134,11,0.55)!important;}
        .nav-link{position:relative;transition:color 0.2s;}
        .nav-link::after{content:'';position:absolute;bottom:-4px;left:0;width:0;height:2px;background:linear-gradient(90deg,#B8860B,#DAA520);border-radius:2px;transition:width 0.3s ease;}
        .nav-link:hover::after,.nav-link.active::after{width:100%;}
        .feature-card{transition:all 0.35s ease;}
        .feature-card:hover{transform:translateY(-6px);box-shadow:0 20px 48px rgba(184,134,11,0.2)!important;}
      `}</style>

      {/* ===== FIXED NAVBAR ===== */}
      <nav style={{ position:"fixed", top:0, left:0, right:0, zIndex:50,
        background:"rgba(253,246,227,0.75)", backdropFilter:"blur(16px)",
        borderBottom:"1px solid rgba(184,134,11,0.2)", boxShadow:"0 2px 20px rgba(184,134,11,0.1)" }}>
        <div style={{ maxWidth:"1200px", margin:"0 auto", padding:"0 1.5rem",
          height:"64px", display:"flex", alignItems:"center", justifyContent:"space-between" }}>

          {/* Logo */}
          <motion.a href="#home" onClick={e=>{e.preventDefault();scrollTo("home");}}
            style={{ display:"flex", alignItems:"center", gap:"0.6rem", textDecoration:"none" }}
            whileHover={{ scale: 1.03 }}>
            <Image src="/drona-logo.png" alt="Drona Logo" width={36} height={36}
              style={{ borderRadius:"50%", boxShadow:"0 2px 12px rgba(184,134,11,0.4)", objectFit:"cover" }} />
            <span style={{ fontFamily:"'Cinzel',serif", fontWeight:800, fontSize:"1.25rem", letterSpacing:"0.1em",
              background:"linear-gradient(135deg,#5C3A00,#8B6914,#DAA520,#B8860B)",
              WebkitBackgroundClip:"text", WebkitTextFillColor:"transparent" }}>DRONA</span>
          </motion.a>

          {/* Desktop nav links */}
          <div style={{ display:"flex", alignItems:"center", gap:"2rem" }} className="hidden md:flex">
            {navLinks.map(n => (
              <a key={n.href} href={n.href}
                onClick={e=>{e.preventDefault();scrollTo(n.href);}}
                className={`nav-link ${activeSection===n.href.replace("#","") ? "active" : ""}`}
                style={{ fontFamily:"'Cinzel',serif", fontSize:"0.72rem", letterSpacing:"0.12em",
                  color:"#6B4F12", textDecoration:"none", fontWeight:600 }}>
                {n.label}
              </a>
            ))}
          </div>

          {/* Sign In */}
          <motion.button id="nav-signin-btn" whileHover={{ scale: 1.05 }} whileTap={{ scale: 0.97 }}
            onClick={() => signIn("google")}
            style={{ display:"flex", alignItems:"center", gap:"0.5rem", padding:"0.5rem 1.25rem",
              borderRadius:"999px", fontSize:"0.8rem", fontWeight:700, letterSpacing:"0.08em",
              fontFamily:"'Cinzel',serif", cursor:"pointer",
              background:"linear-gradient(135deg,#DAA520,#B8860B)",
              color:"#FDF3DC", border:"none",
              boxShadow:"0 2px 14px rgba(184,134,11,0.35)" }}>
            Sign In ✦
          </motion.button>

          {/* Mobile hamburger */}
          <button className="block md:hidden" onClick={()=>setMobileMenuOpen(v=>!v)}
            style={{ background:"none", border:"none", cursor:"pointer", fontSize:"1.4rem", color:"#8B6914" }}>
            {mobileMenuOpen ? "✕" : "☰"}
          </button>
        </div>

        {/* Mobile menu */}
        {mobileMenuOpen && (
          <motion.div initial={{ height:0, opacity:0 }} animate={{ height:"auto", opacity:1 }}
            style={{ background:"rgba(253,246,227,0.95)", borderTop:"1px solid rgba(184,134,11,0.15)", padding:"1rem 1.5rem" }}>
            {navLinks.map(n => (
              <div key={n.href} onClick={()=>scrollTo(n.href)} style={{ padding:"0.6rem 0",
                fontFamily:"'Cinzel',serif", fontSize:"0.8rem", letterSpacing:"0.1em",
                color:"#6B4F12", cursor:"pointer", borderBottom:"1px solid rgba(184,134,11,0.1)" }}>
                {n.label}
              </div>
            ))}
            <button onClick={()=>signIn("google")} style={{ marginTop:"0.75rem", width:"100%",
              background:"linear-gradient(135deg,#DAA520,#B8860B)", color:"#FDF3DC", border:"none",
              borderRadius:"999px", padding:"0.6rem", fontFamily:"'Cinzel',serif",
              fontSize:"0.8rem", fontWeight:700, cursor:"pointer" }}>Sign In ✦</button>
          </motion.div>
        )}
      </nav>

      {/* ===== HERO ===== */}
      <section id="home" ref={heroRef} style={{ minHeight:"100vh", display:"flex", alignItems:"center",
        justifyContent:"center", position:"relative", paddingTop:"80px", overflow:"hidden" }}>

        {/* Background mandala rings */}
        <div style={{ position:"absolute", inset:0, display:"flex", alignItems:"center", justifyContent:"center", pointerEvents:"none", zIndex:0 }}>
          <Mandala size={900} opacity={0.14} speed={140}/>
        </div>
        <div style={{ position:"absolute", inset:0, display:"flex", alignItems:"center", justifyContent:"center", pointerEvents:"none", zIndex:0 }}>
          <motion.div animate={{ rotate: -360 }} transition={{ duration: 80, repeat: Infinity, ease: "linear" }}>
            <Mandala size={560} opacity={0.1} speed={80}/>
          </motion.div>
        </div>

        {/* Archimedean vortex spiral — centred, slowly rotating */}
        <div style={{ position:"absolute", inset:0, display:"flex", alignItems:"center",
          justifyContent:"center", pointerEvents:"none", zIndex:1 }}>
          <VortexSpiral size={820} opacity={0.3} speed={110} />
        </div>

        {/* Second spiral layer — counter-rotating, slightly offset */}
        <div style={{ position:"absolute", inset:0, display:"flex", alignItems:"center",
          justifyContent:"center", pointerEvents:"none", zIndex:1 }}>
          <VortexSpiral size={540} opacity={0.18} speed={75} reverse />
        </div>

        {/* Corner ornaments */}
        <div style={{ position:"fixed", top:60, left:0, pointerEvents:"none", zIndex:0, opacity:0.35 }}><Corner/></div>
        <div style={{ position:"fixed", top:60, right:0, pointerEvents:"none", zIndex:0, opacity:0.35 }}><Corner flip/></div>
        <div style={{ position:"fixed", bottom:0, left:0, pointerEvents:"none", zIndex:0, opacity:0.35 }}><Corner/></div>
        <div style={{ position:"fixed", bottom:0, right:0, pointerEvents:"none", zIndex:0, opacity:0.35 }}><Corner flip/></div>

        {/* Hero content */}
        <motion.div style={{ textAlign:"center", position:"relative", zIndex:2, maxWidth:"720px",
          padding:"0 1.5rem", y: heroY, opacity: heroOpacity }}>

          <motion.p initial={{ opacity:0, y:-10 }} animate={{ opacity:1, y:0 }} transition={{ delay:0.2 }}
            style={{ fontFamily:"'Playfair Display',serif", color:"#8B6914", fontSize:"0.95rem",
              letterSpacing:"0.18em", marginBottom:"0.75rem" }}>
            ✦ AI-Powered Learning Platform ✦
          </motion.p>

          <motion.h1 initial={{ opacity:0, scale:0.88 }} animate={{ opacity:1, scale:1 }}
            transition={{ delay:0.25, duration:0.9 }}
            style={{ fontFamily:"'Cinzel',serif", fontWeight:900, letterSpacing:"0.14em", lineHeight:1.05,
              fontSize:"clamp(3.8rem,11vw,9rem)", marginBottom:"1rem",
              background:"linear-gradient(135deg,#5C3A00 0%,#8B6914 20%,#DAA520 42%,#FFD700 52%,#C9A84C 68%,#8B6914 85%,#5C3A00 100%)",
              backgroundSize:"200% auto", WebkitBackgroundClip:"text", WebkitTextFillColor:"transparent",
              backgroundClip:"text", animation:"goldShimmer 4s linear infinite" }}>
            DRONA
          </motion.h1>

          <motion.p initial={{ opacity:0, y:10 }} animate={{ opacity:1, y:0 }} transition={{ delay:0.5 }}
            style={{ fontFamily:"'Playfair Display',serif", fontSize:"clamp(1rem,2.5vw,1.35rem)",
              color:"#6B4F12", marginBottom:"0.5rem", fontStyle:"italic" }}>
            Your Intelligent Guide to Academic Excellence
          </motion.p>

          <motion.p initial={{ opacity:0 }} animate={{ opacity:0.85 }} transition={{ delay:0.65 }}
            style={{ color:"#8B6914", fontSize:"0.95rem", maxWidth:"480px", margin:"0 auto 2.5rem",
              lineHeight:1.75 }}>
            Personalised study plans, curated free resources, AI-generated mock tests, and intelligent feedback — across 14 subjects, completely free.
          </motion.p>

          {/* CTA */}
          <motion.div initial={{ opacity:0, y:20 }} animate={{ opacity:1, y:0 }} transition={{ delay:0.75 }}
            style={{ display:"flex", flexDirection:"column", alignItems:"center", gap:"0.75rem" }}>
            <motion.button id="hero-begin-btn" onClick={() => signIn("google")}
              whileHover={{ scale:1.04, boxShadow:"0 12px 40px rgba(184,134,11,0.55)" }}
              whileTap={{ scale:0.97 }}
              style={{ background:"linear-gradient(135deg,#8B6914,#B8860B,#DAA520,#C9A84C)",
                color:"#FDF3DC", padding:"1rem 3rem", borderRadius:"999px", border:"none",
                fontFamily:"'Cinzel',serif", fontSize:"1rem", fontWeight:700, letterSpacing:"0.1em",
                cursor:"pointer", boxShadow:"0 6px 28px rgba(184,134,11,0.4)",
                display:"flex", alignItems:"center", gap:"0.6rem" }}>
              ✦ Begin Your Journey
            </motion.button>
          </motion.div>

          {/* Ornamental divider — secular */}
          <motion.div initial={{ opacity:0 }} animate={{ opacity:1 }} transition={{ delay:1 }}
            style={{ display:"flex", alignItems:"center", justifyContent:"center", gap:"1rem", margin:"2.5rem 0 1.5rem" }}>
            <div style={{ height:"1px", width:"80px", background:"linear-gradient(to right,transparent,#B8860B)" }}/>
            <span style={{ color:"#B8860B", fontSize:"1.1rem" }}>✦ ✦ ✦</span>
            <div style={{ height:"1px", width:"80px", background:"linear-gradient(to left,transparent,#B8860B)" }}/>
          </motion.div>

        </motion.div>

      </section>

      {/* ===== FEATURES ===== */}
      <section id="features" style={{ padding:"100px 1.5rem", maxWidth:"1200px", margin:"0 auto" }}>
        <div data-aos style={{ textAlign:"center", marginBottom:"3.5rem" }}>
          <p style={{ fontFamily:"'Cinzel',serif", color:"#B8860B", fontSize:"0.72rem",
            letterSpacing:"0.3em", marginBottom:"0.5rem" }}>✦ HOW DRONA WORKS ✦</p>
          <h2 style={{ fontFamily:"'Playfair Display',serif", fontSize:"clamp(1.8rem,4vw,2.8rem)",
            color:"#5C3A00", fontWeight:700, lineHeight:1.3 }}>
            Everything you need to{" "}
            <em style={{ background:"linear-gradient(135deg,#8B6914,#DAA520,#B8860B)",
              WebkitBackgroundClip:"text", WebkitTextFillColor:"transparent" }}>
              master your exams
            </em>
          </h2>
          <p style={{ color:"#8B6914", marginTop:"0.75rem", opacity:0.8, maxWidth:"480px", margin:"0.75rem auto 0" }}>
            6 powerful AI agents working in harmony for your academic success
          </p>
        </div>

        <div style={{ display:"grid", gridTemplateColumns:"repeat(auto-fill,minmax(300px,1fr))", gap:"1.25rem" }}>
          {features.map((f, i) => (
            <div key={f.id} data-aos data-aos-delay={String(i * 100)}
              className="feature-card" id={`feature-${f.id}`}
              style={{ background:"rgba(253,246,227,0.7)", backdropFilter:"blur(8px)",
                border:"1px solid rgba(184,134,11,0.22)", borderRadius:"20px",
                padding:"1.75rem", position:"relative", overflow:"hidden",
                boxShadow:"0 4px 20px rgba(184,134,11,0.08)" }}>
              <div style={{ position:"absolute", top:"12px", right:"12px", width:"22px", height:"22px",
                borderTop:"1.5px solid rgba(184,134,11,0.4)", borderRight:"1.5px solid rgba(184,134,11,0.4)" }}/>
              <div style={{ position:"absolute", bottom:"12px", left:"12px", width:"22px", height:"22px",
                borderBottom:"1.5px solid rgba(184,134,11,0.4)", borderLeft:"1.5px solid rgba(184,134,11,0.4)" }}/>
              <div style={{ fontSize:"2.4rem", marginBottom:"0.9rem" }}>{f.icon}</div>
              <h3 style={{ fontFamily:"'Playfair Display',serif", fontWeight:700, color:"#5C3A00",
                marginBottom:"0.5rem", fontSize:"1.05rem" }}>{f.title}</h3>
              <p style={{ color:"#7A5C1E", fontSize:"0.85rem", lineHeight:1.75 }}>{f.desc}</p>
            </div>
          ))}
        </div>
      </section>

      {/* ===== SUBJECTS ===== */}
      <section id="subjects" style={{ padding:"80px 1.5rem", textAlign:"center" }}>
        <div data-aos style={{ marginBottom:"3rem" }}>
          <p style={{ fontFamily:"'Cinzel',serif", color:"#B8860B", fontSize:"0.72rem",
            letterSpacing:"0.3em", marginBottom:"0.5rem" }}>✦ AVAILABLE SUBJECTS ✦</p>
          <h2 style={{ fontFamily:"'Playfair Display',serif", fontSize:"clamp(1.8rem,4vw,2.5rem)",
            color:"#5C3A00", fontWeight:700 }}>Choose Your Discipline</h2>
        </div>

        <div style={{ display:"flex", flexWrap:"wrap", justifyContent:"center", gap:"0.75rem",
          maxWidth:"900px", margin:"0 auto" }}>
          {subjects.map((s, i) => (
            <div key={s.name} data-aos data-aos-delay={String(i * 40)}
              className="subject-chip" id={`subject-chip-${s.name.toLowerCase().replace(/[. ]/g,"-")}`}
              style={{ position:"relative", display:"inline-flex", alignItems:"center", gap:"0.4rem",
                padding:"0.5rem 1.1rem", borderRadius:"999px",
                border:"1px solid rgba(184,134,11,0.35)",
                background:"rgba(218,165,32,0.1)", cursor:"default",
                transition:"all 0.25s ease",
                fontFamily:"'Cinzel',serif", fontSize:"0.72rem", letterSpacing:"0.1em",
                color:"#6B4F12", fontWeight:600 }}
              onMouseEnter={e => {
                const el = e.currentTarget as HTMLDivElement;
                el.style.background = "rgba(184,134,11,0.2)";
                el.style.borderColor = "rgba(184,134,11,0.6)";
                el.style.transform = "translateY(-3px) scale(1.05)";
                el.style.boxShadow = "0 6px 20px rgba(184,134,11,0.25)";
              }}
              onMouseLeave={e => {
                const el = e.currentTarget as HTMLDivElement;
                el.style.background = "rgba(218,165,32,0.1)";
                el.style.borderColor = "rgba(184,134,11,0.35)";
                el.style.transform = "";
                el.style.boxShadow = "";
              }}>
              <span style={{ fontSize:"1rem" }}>{s.icon}</span>
              {s.name}
              <div className="chip-tooltip"
                style={{ position:"absolute", bottom:"calc(100% + 8px)", left:"50%",
                  transform:"translateX(-50%) translateY(6px)", background:"rgba(92,58,0,0.9)",
                  color:"#FDF3DC", padding:"0.3rem 0.7rem", borderRadius:"8px",
                  fontSize:"0.65rem", whiteSpace:"nowrap", pointerEvents:"none",
                  opacity:0, transition:"all 0.2s ease",
                  fontFamily:"'Inter',sans-serif", letterSpacing:"0.03em",
                  border:"1px solid rgba(184,134,11,0.4)" }}>
                {s.desc}
                <div style={{ position:"absolute", top:"100%", left:"50%", transform:"translateX(-50%)",
                  border:"5px solid transparent", borderTopColor:"rgba(92,58,0,0.9)" }}/>
              </div>
            </div>
          ))}
        </div>
      </section>

      {/* ===== RESOURCES SECTION ===== */}
      <section id="resources" style={{ padding:"80px 1.5rem", maxWidth:"1000px", margin:"0 auto" }}>
        <div data-aos style={{ textAlign:"center", marginBottom:"3rem" }}>
          <p style={{ fontFamily:"'Cinzel',serif", color:"#B8860B", fontSize:"0.72rem",
            letterSpacing:"0.3em", marginBottom:"0.5rem" }}>✦ LEARNING RESOURCES ✦</p>
          <h2 style={{ fontFamily:"'Playfair Display',serif", fontSize:"clamp(1.8rem,4vw,2.5rem)",
            color:"#5C3A00", fontWeight:700 }}>Free Resources For Every Topic</h2>
          <p style={{ color:"#8B6914", marginTop:"0.75rem", opacity:0.8 }}>
            Curated YouTube lectures — one click away for every topic in your study plan.
          </p>
        </div>
        <div data-aos data-aos-delay="200" style={{ display:"grid", gridTemplateColumns:"repeat(3,1fr)",
          gap:"1rem", background:"rgba(253,246,227,0.6)", border:"1px solid rgba(184,134,11,0.25)",
          borderRadius:"20px", padding:"2rem", backdropFilter:"blur(8px)" }}>
          {["Video Lectures", "Topic Summaries", "Practice Problems", "Reference Notes", "Expert Tutorials", "Past Papers"].map((r, i) => (
            <div key={r} style={{ display:"flex", alignItems:"center", gap:"0.5rem",
              padding:"0.6rem 0.5rem", borderRadius:"10px",
              background:"rgba(218,165,32,0.08)", border:"1px solid rgba(184,134,11,0.15)",
              fontSize:"0.8rem", color:"#6B4F12", fontWeight:500 }}>
              <span>{"📺📝📐📒🎓📋".split("")[i]}</span> {r}
            </div>
          ))}
        </div>
      </section>

      {/* ===== ABOUT ===== */}
      <section id="about" style={{ padding:"80px 1.5rem", maxWidth:"700px", margin:"0 auto", textAlign:"center" }}>
        <div data-aos>
          <p style={{ fontFamily:"'Cinzel',serif", color:"#B8860B", fontSize:"0.72rem",
            letterSpacing:"0.3em", marginBottom:"0.5rem" }}>✦ OUR MISSION ✦</p>
          <h2 style={{ fontFamily:"'Playfair Display',serif", fontSize:"clamp(1.8rem,4vw,2.5rem)",
            color:"#5C3A00", fontWeight:700, marginBottom:"1.25rem" }}>Why Drona?</h2>
          <p style={{ color:"#7A5C1E", lineHeight:1.9, fontSize:"1rem" }}>
            <strong style={{ color:"#5C3A00" }}>Drona</strong> is built on a simple belief — every student deserves a personalised learning experience. Our AI adapts to <em>you</em>, understanding your pace, identifying your weak areas, and guiding you step by step toward academic excellence. No one gets left behind.
          </p>
          <div data-aos data-aos-delay="200" style={{ marginTop:"2rem", display:"flex", justifyContent:"center", gap:"2rem", flexWrap:"wrap" }}>
            {[["14", "Subjects"], ["6", "AI Agents"], ["∞", "Resources"]].map(([n, l]) => (
              <div key={l} style={{ textAlign:"center" }}>
                <div style={{ fontFamily:"'Cinzel',serif", fontSize:"2.5rem", fontWeight:900,
                  background:"linear-gradient(135deg,#8B6914,#DAA520)",
                  WebkitBackgroundClip:"text", WebkitTextFillColor:"transparent" }}>{n}</div>
                <div style={{ color:"#8B6914", fontSize:"0.8rem", letterSpacing:"0.1em" }}>{l}</div>
              </div>
            ))}
          </div>
        </div>
      </section>

      {/* ===== FINAL CTA ===== */}
      <section style={{ padding:"80px 1.5rem 100px", textAlign:"center" }}>
        <motion.div data-aos
          style={{ maxWidth:"600px", margin:"0 auto", padding:"3.5rem 2rem",
            background:"linear-gradient(135deg,rgba(218,165,32,0.15),rgba(184,134,11,0.08))",
            border:"1px solid rgba(184,134,11,0.4)", borderRadius:"28px",
            backdropFilter:"blur(12px)", boxShadow:"0 8px 48px rgba(184,134,11,0.15),inset 0 1px 0 rgba(255,255,255,0.5)" }}>
          <p style={{ fontFamily:"'Cinzel',serif", color:"#B8860B", fontSize:"0.7rem",
            letterSpacing:"0.3em", marginBottom:"1rem" }}>✦ START TODAY ✦</p>
          <h2 style={{ fontFamily:"'Playfair Display',serif", fontSize:"2rem",
            color:"#5C3A00", fontWeight:700, marginBottom:"0.75rem" }}>
            Ready to level up your academics?
          </h2>
          <p style={{ color:"#8B6914", marginBottom:"2rem", lineHeight:1.7 }}>
            Join thousands of students already using Drona — it's completely free.
          </p>
          <motion.button id="cta-signin-btn" onClick={() => signIn("google")}
            whileHover={{ scale:1.04, boxShadow:"0 12px 40px rgba(184,134,11,0.55)" }}
            whileTap={{ scale:0.97 }}
            style={{ background:"linear-gradient(135deg,#8B6914,#B8860B,#DAA520)",
              color:"#FDF3DC", padding:"1rem 2.75rem", borderRadius:"999px",
              border:"none", fontSize:"0.95rem", fontFamily:"'Cinzel',serif",
              fontWeight:700, letterSpacing:"0.08em", cursor:"pointer",
              boxShadow:"0 6px 28px rgba(184,134,11,0.4)" }}>
            ✦ Get Started Free →
          </motion.button>
        </motion.div>
      </section>

      {/* ===== FOOTER ===== */}
      <footer style={{ borderTop:"1px solid rgba(184,134,11,0.15)", padding:"2rem 1.5rem", textAlign:"center" }}>
        <p style={{ fontFamily:"'Cinzel',serif", color:"#B8860B", fontSize:"0.7rem",
          letterSpacing:"0.2em", marginBottom:"0.25rem" }}>✦ DRONA ✦</p>
        <p style={{ color:"#8B6914", fontSize:"0.78rem", opacity:0.7 }}>
          Built with Next.js & Firebase · Powered by Drona AI · Made for every student, everywhere.
        </p>
      </footer>

    </main>
  );
}
